### ISSUE TITLE
Issue in 64 bit version of Office :

### ISSUE THREAD

**Issue by Testcase4** [rmdavy/HeapsOfFun#1]
I tried this solution on office 2013 : 64 bit version and It got crashed. This solution is working on Office 2013 : 32 bit version.
The point where it crashed is : 
retval = HeapWalk(ProcessHeaps, PHE)

Could you please let me know why is this crashed? I tried to debug it but Office suddenly stopped working and could not do it.

**Comment by rmdavy** [comment]
The code needs converting to be x64 compatible.

**Comment by Testcase4** [comment]
I have added one change ( converted Long to LontPtr) to make it run for 64 bit office version. I am facing one issue :
If ReadBuffer = &H49534D41 : This condition is never going to true. Could you please let me know in more detail to debug this issue? Also is there any reference link where I can see how to debug this? 

**PROCESS_HEAP_ENTRY** and **Dim ProcessHeaps As LongPtr** 
Private Type PROCESS_HEAP_ENTRY
    lpData              As LongPtr
    cbData              As LongPtr
    cbOverhead          As Byte
    iRegionIndex        As Byte
    wFlags              As Integer
    dwCommittedSize     As LongPtr
    dwUnCommittedSize   As LongPtr
    lpFirstBlock        As LongPtr
    lpLastBlock         As LongPtr
End Type

**Comment by rmdavy** [comment]
I've just added an x64 compatible version.
